const express = require("express");
const dashboardController = require("../controller/dashboardController");
const auth = require("../middleware/auth");
const router = express.Router();

router.post("/dashboardScope", auth, dashboardController.dashboardScope);
router.post("/dashboardTopEmssion", auth, dashboardController.dashboardTop5);
router.post("/getdashboardfacilities", auth, dashboardController.getdashboardfacilities);
router.post("/ScopewiseEmssion", auth, dashboardController.ScopewiseEmssion);
router.post("/UpDownwiseEmssion", auth, dashboardController.UpDownwiseEmssion);
router.post("/dashboardEmssionByactivities", auth, dashboardController.dashboardEmssionByactivities);
router.post("/dashboardEmssionByVendors", auth, dashboardController.dashboardEmssionByVendors);
router.post("/businessdashboardemssionByTravel", auth, dashboardController.businessdashboardemssionByTravel);
router.post("/businessdashboardemssionByAir", auth, dashboardController.businessdashboardemssionByAir);
router.post("/businessdashboardemssionBygroundTravel", auth, dashboardController.businessdashboardemssionBygroundTravel);
router.post("/businessdashboardemssion", auth, dashboardController.businessdashboardemssion);
router.post("/dashboardWastetop5", auth, dashboardController.dashboardWastetop5);
router.post("/dashboardWasteTotal", auth, dashboardController.dashboardWasteTotal);
router.post("/dashboardWasteEmission", auth, dashboardController.dashboardWasteEmission);
router.post("/dashboardWasteEmissionhaz", auth, dashboardController.dashboardWasteEmissionhaz);
router.post("/dashboardWasteUpDownwiseEmssion", auth, dashboardController.dashboardWasteUpDownwiseEmssion);
router.post("/dashboardWasteBreakdown", auth, dashboardController.dashboardWasteBreakdown);
router.post("/dashboardWaterTotal", auth, dashboardController.dashboardWaterTotal);
router.post("/dashboardWaterwithdrawnby_source", auth, dashboardController.dashboardWaterwithdrawnby_source);
router.post("/dashboardWaterDischargedbydestination", auth, dashboardController.dashboardWaterDischargedbydestination);
router.post("/dashboardWaterTreated_nonTreated", auth, dashboardController.dashboardWaterTreated_nonTreated);
router.post("/dashboardWaterTreatedbydestination", auth, dashboardController.dashboardWaterTreatedbydestination);
router.post("/dashboardWaterTreatedbylevel", auth, dashboardController.dashboardWaterTreatedbylevel);
router.post("/dashboardWaterEmission", auth, dashboardController.dashboardWaterEmission);
router.post("/dashboardenergyConsumption", auth, dashboardController.dashboardenergyConsumption);
router.post("/dashboardenergyConsumptionRenewable", auth, dashboardController.dashboardenergyConsumptionRenewable);
router.post("/dashboardenergyConsumptionWellTank", auth, dashboardController.dashboardenergyConsumptionWellTank);
router.post("/dashboardenergyConsumptionMonth", auth, dashboardController.dashboardenergyConsumptionMonth);
router.post("/dashboardnetZero", auth, dashboardController.dashboardnetZero);
router.post("/dashboardCostcentreBreakdown", auth, dashboardController.dashboardCostcentreBreakdown);
router.post("/getdashboardfacilitiessubgroup", auth, dashboardController.getdashboardfacilitiessubgroup);
router.get("/getFacilityByTenantIdMainGroup/:tenantID", auth, dashboardController.getFacilityByTenantIdMainGroup);
router.get("/getFacilityGroupsByTenantIdAdmin/:tenantID", auth, dashboardController.getFacilityGroupsByTenantIdAdmin);
router.post("/financedashboardemission", auth, dashboardController.financedashboardemission);
router.post("/financedashboardtop5emission", auth, dashboardController.financedashboardtop5emission);

module.exports = router;